# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oueGUJpaSILa6cF98-e9cXSXgTL5OPQ3

# Import numpy, pandas, and matplotlib.pyplot
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

"""# Read the final_dataset csv file"""

final_dts = pd.read_csv ('/content/drive/MyDrive/Colab Notebooks/final-project-dataset/final_dataset.csv')
final_dts

final_dts.info()

"""# Visualization"""

